# .github/workflows/deploy.yml
name: deploy
env:
  DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
            node-version: 16
      - name: Github credentials
        run: |
          git config user.name 'Martin Adams'
          git config user.email 'mdadams10@gmail.com'
          git remote set-url origin https://${DEPLOY_TOKEN}@github.com/mda100/noel-website.git
      - name: Deploy
        run: |
          yarn install
          yarn deploy

