# .github/workflows/deploy.yml
name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
            node-version: 16
      - name: Deploy
        run: |
          yarn install
          yarn deploy