# .github/workflows/deploy.yml
name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
            node-version: 16
      - name: Check github user
        run: |
          git config user.name 'Martin Adams'
          git config user.email 'mdadams10@gmail.com'
      - name: Copy private repo
        run: git clone https://github.com/mda100/noel-website.git
      - name: Deploy
        run: |
          yarn install
          yarn deploy