# .github/workflows/deploy.yml
name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: |
          actions/checkout@v2
          actions/setup-node@v1
      - run: |
          cd ..
          yarn install
          yarn deploy