# .github/workflows/deploy.yml
name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
            node-version: 16
      - name: Github credentials
        run: |
          git config user.name 'Martin Adams'
          git config user.email 'mdadams10@gmail.com'
          git remote add origin https://mda100:NffFrnr68Tg7w7S@github.com/mda100/project.git
      - name: Deploy
        run: |
          yarn install
          yarn deploy

