# .github/workflows/deploy.yml
name: deploy
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ..
          ls
          yarn install
          yarn deploy